---
- name: playbook for frontend
  hosts: frontend
  become: true
  vars:
    - foo: boo
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Do default site as forbiden
      copy:
        src: default.j2
        dest: /etc/nginx/sites-available/default
    - name: Restart nginx after redeploy config
      service:
        name: nginx
        state: restarted
